services:
  madrs_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  madrs_app:
    image: madrs_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - madrs_database
    environment:
      IS_DOCKER_CONTAINER: true
      DATABASE_URL: postgresql+psycopg://app_user:app_password@madrs_database:5432/app_db

volumes:
  pgdata: