"""refactor: table books

Revision ID: ea4a9b42fc47
Revises: db4f0cf32865
Create Date: 2025-08-27 10:46:16.424512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4a9b42fc47'
down_revision: Union[str, Sequence[str], None] = 'db4f0cf32865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('ano', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('titulo', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'books', ['titulo'])
    op.drop_column('books', 'year')
    op.drop_column('books', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('books', sa.Column('year', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'titulo')
    op.drop_column('books', 'ano')
    # ### end Alembic commands ###
